### ISSUE TITLE
Binnies mods seems to be updated 

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/ArchDreamCraft#10]
Maybe we have to check Binnies mods again. An Update is available on his site.

**Comment by Methes** [comment]
Binnie567 did update and probably solved the issue with long loading times. He used to have other bugs in his mod as well so I'll check them.
I'm not sure we need the mod though. Genetic machines are covered with Gendustry. Bees from ExtraBees and MagicBees overlap a bit. Botania has just aesthetic function atm.
I'll get home to my PC this evening so I'll check it more thoroughly.

**Comment by Dream-Master** [comment]
Ok I think binnie Mods is not a must have mod any more because they update not recently enough. So never mind my Question.
