### ISSUE TITLE
IHL and Greg's Lighting.

### ISSUE THREAD

**Issue by Methes** [Dream-Master/ArchDreamCraft#11]
Another suggestion came to my mind: GT addon called IHL http://forum.industrial-craft.net/index.php?page=Thread&threadID=10458

This mod adds nifty little gadgets such as:
Autocharger of electric items and drones.
Drones that pick up stuff and put it into inventory (require EU to run and are Tech golems basically).
Tunneling shield - basically a RC Bore that runs on EU.
Automatic (EU) way of collecting sticky resin from trees.
Fan running on EU with advanced mechanics (variable air flow and strength depending on tunnel size).
Handpump allowing you to suck surrounding liquids into cells, picks up source blocks when applied to flowing liquids (runs on EU).
Transdimensional item teleporter - replaces missing GT tesseract.
Adding a few recipes to GT chemistry.
New mob - Wailer - that spawns in the End and is very powerful.
Water mechanics - source blocks are affected by gravity (usually disabled).

Everything is configurable and the mod has GT recipes already.
Kirara uses this mod so that's why it came to my mind.

And about Greg's Lighting - it adds a floodlight running on gas or EU that is a Techy alternative to Thaumcraft Lamp.

**Comment by Dream-Master** [comment]
I know this Mod and we test it on my other Server before(IHL). After a few weeks we delete it i dont know the Reason anymore. Maybe we have to give this mod a try. Greg's lighting I look into that later.
