### ISSUE TITLE
Bowstring and Fletching

### ISSUE THREAD

**Issue by Methes** [Dream-Master/ArchDreamCraft#9]
Enchanted Bowstring and Leaf Fletching are both usable only to create casts.
That is a bug and it's present because they have metadata :1 so they get disabled by default.
On top of that, there is no usage for casts in bowstrings and fletching.
I've searched the Tweaks configs but couldn't find any option for that.

**Comment by Dream-Master** [comment]
What do you mean with lag on forestrys Bags?

**Comment by Methes** [comment]
I'm not sure who it happened to but I think it was Drobac so he can give you more info.
Guys said that as he had 9 bags in his inventory, every picked up block had to check all the slots in those 9 bags to see if it fits there, creating huge load on the server.

**Comment by Dream-Master** [comment]
So we have new Players ? Ok than its ok that it's lag because otherwise the Bag is overpowered .
